# Generated by Django 2.2.7 on 2019-11-28 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
